### ISSUE TITLE
Web Crawlers (Reddit, Twitter)

### ISSUE THREAD

**Issue by utkn** [Sierox/cryptocurrency-manipulation-detection#1]
Preliminary implementation of web crawlers for the following websites:
* Reddit
* Twitter

The crawlers should gather posts from important cryptocurrency groups and convert these posts into the following format:
* Poster: Name of the poster.
* Source: Reddit or twitter.
* Contents: The contents of the post.
* Interaction: The number of replies/likes that the post has received.
* Time: UNIX timestamp of the post (with minute accuracy)

**Comment by Tolgino** [comment]
Reddit done
